#version: 2.1

#orbs:
 #   hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

#workflows:
#    "Hello Workflow":
#        jobs:
#          - hello/hello-build

version: 2  # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: circleci/node:10.0-browsers
      #-image: leyo007/get-started:part2
    steps: # steps that comprise the `build` job
#new start
  - run:
      name: Setup Environment Variables
      command: |
        echo 'export PATH="$GOPATH/bin:$PATH"' >> $BASH_ENV
        echo 'export GIT_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
#new end        
#      - checkout # check out source code to working directory
#      # Run a step to setup an environment variable.
#      - run: 
#          name: "Setup custom environment variables"
#          command: |
#            echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
#      # Run a step to print what branch our code base is on.
#      - run: # test what branch we're on.
#          name: "What branch am I on?"
#          command: echo ${CIRCLE_BRANCH}
#      # Run another step, the same as above; note that you can
#      # invoke environment variable without curly braces.
#      - run:
#          name: "What branch am I on now?"
#          command: echo $CIRCLE_BRANCH
#      - run:
#          name: "What was my custom environment variable?"
#          command: echo ${MY_ENV_VAR}
