version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u leyo007 --password-stdin
         docker run -d leyo007/get-started:part2


     # build the application image
     - run: docker build --tag=friendlyhello .

     # deploy the image
     #- run: docker push company/app:$CIRCLE_BRANCH
